name: todo_alarm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  alarm: ^5.1.5
  auto_start_flutter: ^0.1.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^3.0.3
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.3
  riverpod_generator: ^3.0.3
  shared_preferences: ^2.5.3
  speech_to_text: ^7.3.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
