name: todo_alarm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  alarm: ^5.1.5
  flutter:
    sdk: flutter
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  riverpod_generator: ^3.0.3
  shared_preferences: ^2.5.3
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
